### ISSUE TITLE
Bug: fail with pip>= 21.3

### ISSUE THREAD

**Issue by Niccolum** [FHPythonUtils/LicenseCheck#17]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Ubuntu 18 LTS
- Version: 2021.5

### Describe the bug
New pip broke internal API. Similar issue with https://github.com/jazzband/pip-tools/issues/1503

### Expected outcome
Zero code or lisencecheck output

### Actual outcome
```
licensecheck.............................................................Failed
- hook id: licensecheck
- exit code: 1

Traceback (most recent call last):
  File "/home/niccolum/.cache/pre-commit/repohao7hzis/py_env-python3.10/bin/licensecheck", line 5, in <module>
    from licensecheck import cli
  File "/home/niccolum/.cache/pre-commit/repohao7hzis/py_env-python3.10/lib/python3.10/site-packages/licensecheck/__init__.py", line 12, in <module>
    from licensecheck import formatter, get_deps
  File "/home/niccolum/.cache/pre-commit/repohao7hzis/py_env-python3.10/lib/python3.10/site-packages/licensecheck/get_deps.py", line 10, in <module>
    from licensecheck import license_matrix, packageinfo
  File "/home/niccolum/.cache/pre-commit/repohao7hzis/py_env-python3.10/lib/python3.10/site-packages/licensecheck/packageinfo.py", line 15, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/home/niccolum/.cache/pre-commit/repohao7hzis/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/utils/misc.py)
```

**Comment by FredHappyface** [comment]
Cheers for the report

Can you upgrade to 2021.5.2 please? Should be fixed in the most recent version as noted in the changelog. Thanks 😊

**Comment by Niccolum** [comment]
Ok, check today, thanks!

**Comment by Niccolum** [comment]
@FredHappyface can you add new tag 2021.5.2 for master? In precommit i can use tag instead of package version.

**Comment by FredHappyface** [comment]
Oh yeah, of course!

Sorry about that, completely forgot!

**Comment by FredHappyface** [comment]
#fixed in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2021.5.2
