### ISSUE TITLE
Bug: Packages parsed by importlib as MultiplexedPath cannot have module size read properly.

### ISSUE THREAD

**Issue by RaczeQ** [FHPythonUtils/LicenseCheck#30]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info
- OS: Ubuntu
- Version: 20.04

### Describe the bug

Package `mkdocstrings` is interpreted by importlib as a `importlib.readers.MultiplexedPath` and isn't cast to `pathlib.Path` type with `glob` attribute.

Error during evaluation:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../.venv/lib/python3.8/site-packages/licensecheck/__main__.py", line 6, in <module>
    cli()
  File ".../.venv/lib/python3.8/site-packages/licensecheck/__init__.py", line 90, in cli
    depsWithLicenses = get_deps.getDepsWithLicenses(
  File ".../.venv/lib/python3.8/site-packages/licensecheck/get_deps.py", line 116, in getDepsWithLicenses
    packages = packageinfo.getPackages(reqs)
  File ".../.venv/lib/python3.8/site-packages/licensecheck/packageinfo.py", line 122, in getPackages
    packageinfo.add(getPackageInfoLocal(requirement))
  File ".../.venv/lib/python3.8/site-packages/licensecheck/packageinfo.py", line 46, in getPackageInfoLocal
    size = getModuleSize(cast(Path, packagePath), name)
  File ".../.venv/lib/python3.8/site-packages/licensecheck/packageinfo.py", line 188, in getModuleSize
    for f in path.glob("**/*")
AttributeError: 'MultiplexedPath' object has no attribute 'glob'
```

### Expected outcome

Skip and download info from PyPI site.

### Actual outcome

`AttributeError` is thrown and the code stops execution.

**Comment by FredHappyface** [comment]
Hi thanks again for the pr for this. Going to close this now as that has been merged. Feel free to reopen if you need to! 😊
