### ISSUE TITLE
Bug: Package parsing results in an exception when "celery" is added to a poetry project

### ISSUE THREAD

**Issue by dkmorgan** [FHPythonUtils/LicenseCheck#36]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Ubuntu
- Version: 20.04

### Describe the bug
`licensecheck` command fails following the addition of the `celery` package to a poetry project.

```bash
$ poetry add Celery
Using version ^5.2.7 for celery

Updating dependencies
Resolving dependencies... (0.8s)

Writing lock file

Package operations: 10 installs, 0 updates, 0 removals

  • Installing vine (5.0.0)
  • Installing wcwidth (0.2.6)
  • Installing amqp (5.1.1)
  • Installing prompt-toolkit (3.0.38)
  • Installing billiard (3.6.4.0)
  • Installing click-didyoumean (0.3.0)
  • Installing click-plugins (1.1.1)
  • Installing click-repl (0.2.0)
  • Installing kombu (5.2.4)
  • Installing celery (5.2.7)

$ licensecheck
Enter the project license
>Proprietary
Traceback (most recent call last):
  File ".../.venv/bin/licensecheck", line 8, in <module>
    sys.exit(cli())
  File ".../.venv/lib/python3.10/site-packages/licensecheck/__init__.py", line 90, in cli
    depsWithLicenses = get_deps.getDepsWithLicenses(
  File ".../.venv/lib/python3.10/site-packages/licensecheck/get_deps.py", line 131, in getDepsWithLicenses
    packages = packageinfo.getPackages(reqs)
  File ".../.venv/lib/python3.10/site-packages/licensecheck/packageinfo.py", line 117, in getPackages
    packageinfo.add(getPackageInfoLocal(requirement))
  File ".../.venv/lib/python3.10/site-packages/licensecheck/packageinfo.py", line 42, in getPackageInfoLocal
    packagePath = ilr.files(requirement)
  File "/usr/lib/python3.10/importlib/_common.py", line 22, in files
    return from_package(get_package(package))
  File "/usr/lib/python3.10/importlib/_common.py", line 67, in get_package
    if wrap_spec(resolved).submodule_search_locations is None:
  File "/usr/lib/python3.10/importlib/_adapters.py", line 16, in __getattr__
    return getattr(self.spec, name)
AttributeError: 'NoneType' object has no attribute 'submodule_search_locations'
```

### Expected outcome

The `licensecheck` command should complete successfully and output the license details of main packages in the poetry project.

### Actual outcome

The `licensecheck` command fails with a runtime exception.

**Comment by FredHappyface** [comment]
Fixed as a happy side effect of the latest release `2023.1.2`

![image](https://github.com/FHPythonUtils/LicenseCheck/assets/41634689/3c366387-c158-4adb-82c1-41112f3cb8b7)
