### ISSUE TITLE
Bug: sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by sgaechter** [FHPythonUtils/LicenseCheck#70]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [X ] I have checked for similar issues in the project's issue tracker.
- [ X] I have searched closed issues to see if a similar problem was reported
  before.

## Issue Details

Error running licensecheck on Python 3.12 (Windos)

### Description

on CMD in project folder: "licensecheck" causing error

### Expected Behavior

licensecheck shows all licenses, as described in readme.

### Actual Behavior

Error occours:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\licensecheck.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\licensecheck\__init__.py", line 13, in <module>
    from licensecheck import formatter, get_deps, types
  File "C:\Python312\Lib\site-packages\licensecheck\formatter.py", line 35, in <module>
    from licensecheck.types import License, PackageInfo, printLicense
  File "C:\Python312\Lib\site-packages\licensecheck\types.py", line 14, in <module>
    session = requests_cache.CachedSession(f"{THISDIR}/licensecheck")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests_cache\session.py", line 61, in __init__
    self.cache = init_backend(cache_name, backend, serializer=serializer, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests_cache\backends\__init__.py", line 91, in init_backend
    return BACKEND_CLASSES[backend](cache_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests_cache\backends\sqlite.py", line 61, in __init__
    self.responses: SQLiteDict = SQLiteDict(db_path, table_name='responses', **skwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests_cache\backends\sqlite.py", line 225, in __init__
    self.init_db()
  File "C:\Python312\Lib\site-packages\requests_cache\backends\sqlite.py", line 230, in init_db
    with self.connection(commit=True) as con:
  File "C:\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\requests_cache\backends\sqlite.py", line 252, in connection
    self._connection = sqlite3.connect(self.db_path, **self.connection_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

## System Information

Please provide the following additional information about your system or
environment:

- Operating System (OS): Windows 11
- Project Version (if applicable): 2024

**Comment by FredHappyface** [comment]
Hey thanks for this. Looks to be an issue with the requests cache library opening the db 

Related to https://github.com/requests-cache/requests-cache/issues/894

**Comment by FredHappyface** [comment]
Do you have a sqlite db under `C:\Python312\Lib\site-packages\licensecheck\` ? As that is where python is trying to create it (i.e. with the library). This is probably to do with perms on that directory so may be to do with how you installed python? Or a windows 11 change? (I can only test in linux vms and Windows 10, unfortunately so cannot investigate that)

**Comment by FredHappyface** [comment]
Looks like https://pypi.org/project/appdirs/ might be exactly what's needed! :)

**Comment by FredHappyface** [comment]
Fingers crossed its sorted in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.1.2 !

At minimum, we write to appdata now :) 

```
C:\Users\{user}\AppData\Local\fredhappyface\licensecheck
```

C:\Users\Dell\AppData\Local\fredhappyface\licensecheck

**Comment by sgaechter** [comment]
Dear @FredHappyface 

The latest Release fixed the problem under Windows. Thanks for the quick fix.

**Comment by FredHappyface** [comment]
Whoop! Glad to hear it!

Thanks again for raising this

Now just a case of fixing this in a couple other libs :)
